version: '3'
services:

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mysql-service
    volumes:
     - ./my-database:/var/lib/mysql
    ports:
      - 3306:3306
    networks: 
      - stack

  app:
    tty: true
    restart: always
    build:
      context: ./web/app_web
      dockerfile: Dockerfile
    container_name: app-symfony
    volumes:
      - ./web/app_web:/code
    ports:
      - 8000:8000
    networks:
      - stack


networks:
  stack:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.97.0.1/16