<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0vOmSj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0vOmSj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0vOmSj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0vOmSj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0vOmSj\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0vOmSj',
    'container.build_id' => 'b34c4725',
    'container.build_time' => 1615783487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0vOmSj');
